# Generated by Django 4.1.4 on 2023-05-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('C', 'Completed')], default='P', max_length=1),
        ),
    ]
