# Generated by Django 4.1.7 on 2023-05-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskList', '0002_alter_tasklist_assigned_to_alter_tasklist_status'),
        ('taskList', '0002_alter_tasklist_status'),
    ]

    operations = [
    ]
